name: Documentation
on: 
    push:
        branches-ignore: 
            - main
jobs:
    resources:
        name: Update Documentation
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - uses: actions/setup-node@v1

            - name: Install jsdoc
              run: npm install

            - name: Generate Server Documentation
              run: npm run doc-server

            - name: Generate Client Documentation
              run: npm run doc-client
              
            - name: Upload Client Docs
              uses: actions/upload-artifact@v2
              with:
                name: trouble-client-docs
                path: docs/client/ 
                if-no-files-found: error    # Flag an error if docs were not generated
              
            - name: Upload Server Docs
              uses: actions/upload-artifact@v2
              with:
                name: trouble-server-docs
                path: docs/stuff/ 
                if-no-files-found: error    # Flag an error if docs were not generated
